name: Update README Status

on:
  schedule:
    # Runs every day at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Update README date
      run: |
        sed -i "/Last checked:/c\Last checked: $(date +'%B %d, %Y')" README.md

    - name: Commit and push
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<raxxla.offical@gmail.com>"
        git add README.md
        git commit -m "Checked Status & Updated README date" || echo "No changes to commit"
        git push
